// Configuration for Snow Globe Collection

// Google Sheets CSV URL
const SHEET_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQodB81nwsmqRIw4dE_HUsbDt7kOhSEsRcq0yilv-F037j7cXWvYMiceHYq_zwSh3klICQ2OQokHJvR/pub?gid=302830052&single=true&output=csv';

// Country flag emojis
const COUNTRY_FLAGS = {
    'Russia': '🇷🇺',
    'Italy': '🇮🇹',
    'France': '🇫🇷',
    'Hungary': '🇭🇺',
    'Spain': '🇪🇸',
    'Germany': '🇩🇪',
    'Austria': '🇦🇹',
    'Switzerland': '🇨🇭',
    'Netherlands': '🇳🇱',
    'Belgium': '🇧🇪',
    'Czech Republic': '🇨🇿',
    'Poland': '🇵🇱',
    'Portugal': '🇵🇹',
    'Greece': '🇬🇷',
    'Turkey': '🇹🇷',
    'United Kingdom': '🇬🇧',
    'Ireland': '🇮🇪',
    'Denmark': '🇩🇰',
    'Sweden': '🇸🇪',
    'Norway': '🇳🇴',
    'Finland': '🇫🇮',
    'Iceland': '🇮🇸',
    'Croatia': '🇭🇷',
    'Slovenia': '🇸🇮',
    'Romania': '🇷🇴',
    'Bulgaria': '🇧🇬',
    'Serbia': '🇷🇸',
    'Ukraine': '🇺🇦',
    'China': '🇨🇳',
    'Japan': '🇯🇵',
    'South Korea': '🇰🇷',
    'Thailand': '🇹🇭',
    'Vietnam': '🇻🇳',
    'Singapore': '🇸🇬',
    'Malaysia': '🇲🇾',
    'Indonesia': '🇮🇩',
    'Philippines': '🇵🇭',
    'India': '🇮🇳',
    'Nepal': '🇳🇵',
    'Sri Lanka': '🇱🇰',
    'United Arab Emirates': '🇦🇪',
    'Israel': '🇮🇱',
    'Jordan': '🇯🇴',
    'USA': '🇺🇸',
    'United States': '🇺🇸',
    'Canada': '🇨🇦',
    'Mexico': '🇲🇽',
    'Brazil': '🇧🇷',
    'Argentina': '🇦🇷',
    'Chile': '🇨🇱',
    'Peru': '🇵🇪',
    'Colombia': '🇨🇴',
    'Ecuador': '🇪🇨',
    'Australia': '🇦🇺',
    'New Zealand': '🇳🇿',
    'Egypt': '🇪🇬',
    'Morocco': '🇲🇦',
    'South Africa': '🇿🇦',
    'Kenya': '🇰🇪',
    'Tanzania': '🇹🇿',
    'Tunisia': '🇹🇳'
};

// Continent colors - Snowflake inspired palette
const CONTINENT_COLORS = {
    'Europe': { color: '#0ea5e9', class: 'europe', name: 'Europe' },
    'Asia': { color: '#f97316', class: 'asia', name: 'Asia' },
    'Africa': { color: '#10b981', class: 'africa', name: 'Africa' },
    'North America': { color: '#ef4444', class: 'north-america', name: 'North America' },
    'South America': { color: '#8b5cf6', class: 'south-america', name: 'South America' },
    'Oceania': { color: '#06b6d4', class: 'oceania', name: 'Oceania' }
};
